language: ruby
rvm:
- 2.1.5
addons:
  postgresql: '9.3'
  code_climate:
    repo_token:
      secure: PK/YJYSCEQ0/pRrFhruasAp91P/6MRPowVoC3fVU1fCa8CoZmck8YCbDIUkuCQhRFfbUb6ggg3yGmwSrX+WcKXwzEzvO88zUv1rb+wRey/hxzrH8f67e2d03eNDGhDSXDBxp16yTGzgGoOIkTofOS1PhwFF1FWIZ4azcxpaMMjM=
install:
- npm install
- npm run bundle
- bundle install --without development --deployment
before_script:
- psql -c 'create database asm_test;' -U postgres
- cp config/database.yml.travis config/database.yml
- bin/rake db:schema:load
cache:
  directories:
  - vendor/bundle
  - node_modules
services:
- redis-server
- elasticsearch
deploy:
  provider: heroku
  strategy: git
  app:
    secure: gv+O69pvNInWcQUSRwjPS2Fu+5gKwSTkiEzQ8KkOMygBTa1btS8DWpvQUtkxtEyXDwTz7P5UNYNNsRcL1/UCB6Xl3UknnTK825yTMfX3UDKAhNQ0+Zw0GtqXx9xXnfPthhBYGK7g2aKhoou4eJwkDIBVytmMsTxFj+fwnTSRnRo=
  run:
    - rake db:migrate
    - restart
    - rake cleanup
  api_key:
    secure: V8u9b4ILMBW4EMofqRlm3XBgQIBM0P5Ewa4ETeKiESb0PwkGVw7KXIWW571pzXpw0+Z7aDNQlmAbF4OQljXasg4B+V0h69AvoEaXfOVhZPbdLn//zXdcbh71vV3bIhyOhXrWzbrhsVLuEgc5w1Wgq5bx4um5DVkPrIid0m0nyRk=
notifications:
  slack:
    secure: h95nBI0PTGK/rUpx5Jig71L2TPEh0JRh15oxdY27SV8fsHlENozydvfEKgpk5CR6hyc0LsJMBVhEubiN3G5Ob/G1A8skngCIIs8VVCKdUbUXd+PGTcx52XldjRkmVAKXAXeDOv3jajC2h0872YfgjTVtCpIcv8oXTVANU+aoX28=
    on_success: change
    on_failure: always
env:
  global:
    secure: e5U3AYlkOhCiDJxHnR+tAkARa+EL3mcKYQujnerIkXxcCHz2D2cRgYutGYb6sfZxZaspZsk62EyxGTeEcCJP5D5ANaOkpQ4qdSjznHRJdjiEcM2+XBUsRXgTQeeXbtpG5uW+gX9DlFf0e1149RHXErdR0WiUdrHpRKnAU8LOV48=
